FROM quay.io/openshiftio/fabric8-analytics-f8a-emr-deployment:latest

LABEL MAINTAINER="Sunil Samal <ssamal@redhat.com>"

# --------------------------------------------------------------------------------------------------
# copy testing source code and scripts into root dir /
# --------------------------------------------------------------------------------------------------
ADD ./tests/ /tests
ADD ./.git/ /.git
ADD ./tests/scripts/entrypoint-test.sh /entrypoint-test.sh
RUN chmod 0777 /entrypoint-test.sh

ENV PYTHONPATH=/

RUN pip3 install git+https://github.com/fabric8-analytics/fabric8-analytics-auth.git@ad3dab5#egg=fabric8a_auth

RUN pip3 install git+https://github.com/fabric8-analytics/fabric8-analytics-rudra.git@e9a9239#egg=rudra

RUN pip3 install pytest pytest-cov radon==2.4.0 faker mock

# --------------------------------------------------------------------------------------------------
# RUN THE UNIT TESTS
# --------------------------------------------------------------------------------------------------
ENTRYPOINT ["/entrypoint-test.sh"]
